CREATE ROLE storyos_owner NOLOGIN;
CREATE ROLE storyos_runtime LOGIN NOSUPERUSER NOBYPASSRLS;
CREATE ROLE storyos_backup LOGIN NOSUPERUSER NOBYPASSRLS REPLICATION;
CREATE ROLE storyos_restore LOGIN NOSUPERUSER NOBYPASSRLS;
