[package]
name = "storyos-worker"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
storyos-adapter-postgres = { path = "../storyos-adapter-postgres" }
storyos-application = { path = "../storyos-application" }
tokio = { workspace = true, features = ["time"] }

[lints]
workspace = true
