[package]
name = "storyos-adapter-postgres"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
sha2.workspace = true
serde_json.workspace = true
storyos-application = { path = "../storyos-application" }
storyos-core = { path = "../storyos-core" }
tokio.workspace = true
tokio-postgres.workspace = true

[lints]
workspace = true
