pub(super) fn release_profile_declaration_bytes() -> Vec<u8> {
    concat!(
        "// @generated by storyos-contracts; do not edit.\n",
        "import type { Release1ProtocolProfile } from \"./client.mjs\";\n",
        "export declare const RELEASE_1_PROTOCOL_PROFILE: ",
        "Readonly<Release1ProtocolProfile>;\n",
    )
    .as_bytes()
    .to_vec()
}
