pub(super) const CONTRACT_REVISION: &str =
    "stage1-production-shaped-manual-editor-risk-slice-2026-08-04-v5";
pub(super) const BASELINE_COMMIT: &str = "af50f2340a8ef0775fc344bc374390fe1d355e49";
pub(super) const BASELINE_TREE: &str = "0d0ed71354194f7b4289a5cb859644784c39ae70";
pub(super) const ISSUE_BODY_SHA256: &str =
    "e913ec0fb61a558e1ab07a648ee8f7dc59fc04125da1fab1b10c6efd239882f1";
pub(super) const ROUTE_CATALOG_PATH: &str =
    "docs/foundation/versioned-protocol-release-1-route-catalog.json";
pub(super) const PERSISTENCE_CATALOG_PATH: &str =
    "docs/foundation/postgresql-release-1-persistence-catalog.json";

pub(super) const SOURCE_PATHS: &[&str] = &[
    "AGENTS.md",
    "CONTEXT.md",
    "GOAL.md",
    "docs/agents/issue-tracker.md",
    "docs/adr/0004-adopt-postgresql-service-and-project-isolation-boundary.md",
    "docs/adr/0006-adopt-foundation-monorepo-governance.md",
    "docs/adr/0007-preserve-process-separable-server-worker-boundary.md",
    "docs/adr/0009-require-snapshot-resync-at-replay-generation-boundaries.md",
    "docs/adr/0010-require-lifecycle-proof-before-recovery-visibility.md",
    "docs/adr/0012-adopt-deterministic-contract-verification.md",
    "docs/adr/0013-trust-the-storyos-web-client-for-author-command-admission.md",
    "docs/foundation/ai-independent-editor-first-release-baseline-and-handoff-criteria.md",
    "docs/foundation/author-command-admission.md",
    "docs/foundation/deterministic-verification-and-failure-recovery-gates.md",
    "docs/foundation/manuscript-revision-proposal-state-machine.md",
    "docs/foundation/modular-monolith-and-repository-governance-boundaries.md",
    "docs/foundation/postgresql-project-storage-isolation-and-migration-contract.md",
    PERSISTENCE_CATALOG_PATH,
    "docs/foundation/run-event-mailbox-snapshot-retention-and-archival-semantics.md",
    "docs/foundation/storyos-service-client-external-trust-boundaries-threat-model.md",
    ROUTE_CATALOG_PATH,
    "docs/foundation/versioned-command-query-artifact-event-protocol.md",
    "docs/foundation/web-editor-session-synchronization-and-recovery-semantics.md",
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) struct OperationExpectation {
    pub(super) operation_id: &'static str,
    pub(super) kind: &'static str,
    pub(super) method: &'static str,
    pub(super) path: &'static str,
    pub(super) request_schema: &'static str,
    pub(super) response_schema: &'static str,
    pub(super) semantic_owner: &'static str,
    pub(super) error_profile: &'static str,
    pub(super) project_scope: &'static str,
}

pub(super) const OPERATIONS: &[OperationExpectation] = &[
    OperationExpectation {
        operation_id: "getProtocolProfile",
        kind: "query",
        method: "GET",
        path: "/api/v1/protocol",
        request_schema: "storyos.query.protocol-profile.request.v1",
        response_schema: "storyos.query.protocol-profile.response.v1",
        semantic_owner: "protocol",
        error_profile: "query_protocol",
        project_scope: "project-free",
    },
    OperationExpectation {
        operation_id: "getProject",
        kind: "query",
        method: "GET",
        path: "/api/v1/projects/{project_id}",
        request_schema: "storyos.query.project.request.v1",
        response_schema: "storyos.query.project.response.v1",
        semantic_owner: "release",
        error_profile: "query_canonical",
        project_scope: "exact-owner-user-id-and-project-id",
    },
    OperationExpectation {
        operation_id: "getChapter",
        kind: "query",
        method: "GET",
        path: "/api/v1/projects/{project_id}/chapters/{chapter_id}",
        request_schema: "storyos.query.chapter.request.v1",
        response_schema: "storyos.query.chapter.response.v1",
        semantic_owner: "release",
        error_profile: "query_canonical",
        project_scope: "exact-owner-user-id-and-project-id",
    },
    OperationExpectation {
        operation_id: "createEditorSession",
        kind: "command",
        method: "POST",
        path: "/api/v1/projects/{project_id}/editor-sessions",
        request_schema: "storyos.command.create-editor-session.request.v1",
        response_schema: "storyos.command.create-editor-session.response.v1",
        semantic_owner: "editor",
        error_profile: "session_control",
        project_scope: "exact-owner-user-id-and-project-id",
    },
    OperationExpectation {
        operation_id: "getEditorSession",
        kind: "query",
        method: "GET",
        path: "/api/v1/projects/{project_id}/editor-sessions/{editor_session_id}",
        request_schema: "storyos.query.editor-session.request.v1",
        response_schema: "storyos.query.editor-session.response.v1",
        semantic_owner: "editor",
        error_profile: "query_canonical",
        project_scope: "exact-owner-user-id-and-project-id",
    },
    OperationExpectation {
        operation_id: "createProjectCommandChallenge",
        kind: "challenge",
        method: "POST",
        path: "/api/v1/projects/{project_id}/anti-forgery-challenges",
        request_schema: "storyos.challenge.project-command-anti-forgery-challenge.request.v1",
        response_schema: "storyos.challenge.project-command-anti-forgery-challenge.response.v1",
        semantic_owner: "admission",
        error_profile: "challenge",
        project_scope: "exact-owner-user-id-and-project-id",
    },
    OperationExpectation {
        operation_id: "applyAuthorEdit",
        kind: "command",
        method: "POST",
        path: "/api/v1/projects/{project_id}/manuscript/author-edits",
        request_schema: "storyos.command.apply-author-edit.request.v1",
        response_schema: "storyos.command.apply-author-edit.response.v1",
        semantic_owner: "core",
        error_profile: "editor_command",
        project_scope: "exact-owner-user-id-and-project-id",
    },
    OperationExpectation {
        operation_id: "getCommand",
        kind: "query",
        method: "GET",
        path: "/api/v1/projects/{project_id}/commands/{command_id}",
        request_schema: "storyos.query.command.request.v1",
        response_schema: "storyos.query.command.response.v1",
        semantic_owner: "admission",
        error_profile: "query_canonical",
        project_scope: "exact-owner-user-id-and-project-id",
    },
    OperationExpectation {
        operation_id: "activityStream",
        kind: "stream",
        method: "GET",
        path: "/api/v1/projects/{project_id}/activity",
        request_schema: "storyos.stream.activity-stream.request.v1",
        response_schema: "storyos.stream.activity-stream.response.v1",
        semantic_owner: "replay",
        error_profile: "stream",
        project_scope: "exact-owner-user-id-and-project-id",
    },
    OperationExpectation {
        operation_id: "getSnapshot",
        kind: "query",
        method: "GET",
        path: "/api/v1/projects/{project_id}/snapshots/{snapshot_id}",
        request_schema: "storyos.query.snapshot.request.v1",
        response_schema: "storyos.query.snapshot.response.v1",
        semantic_owner: "replay",
        error_profile: "query_canonical",
        project_scope: "exact-owner-user-id-and-project-id",
    },
];
