use super::{
    ACCEPT, ADMITTED_TARGET, Binding, CANCEL, CANDIDATE_EDIT, CAPTURED_MEMORY, COMPACT, COMPARISON,
    CONTINUE, CONTINUE_GENERATION, CREATE_RUN, EXPIRY, EvidenceClass, FAKE_DECISION, INLINE,
    INLINE_PRODUCTION, LOOKUP, MULTI, OPEN_BLOCK, PARTIAL, PHYSICAL_DRILL, PHYSICAL_SCRIPT,
    PRODUCTION_HOST, PROOF, REJECT, RUN_EVIDENCE, STAGE2_JOURNEY, STREAM, SUCCESSOR, TICKET_ISSUE,
    UNDO, WITHDRAW, WORKSPACE,
};

macro_rules! issue {
    ($number:literal) => {
        concat!("https://github.com/FrankQDWang/StoryOS/issues/", $number)
    };
}

pub(super) const BINDINGS: &[Binding] = &[
    Binding {
        id: "REL-007",
        owners: &["OWN-REL", "OWN-DVG", "OWN-GOV"],
        implementation_issues: &[issue!("62"), TICKET_ISSUE],
        evidence: PROOF,
        supporting_evidence: &[],
        evidence_class: EvidenceClass::Contract,
    },
    Binding {
        id: "S3-REQ-001",
        owners: &["OWN-REL", "OWN-AGENT", "OWN-WEB"],
        implementation_issues: &[issue!("374"), issue!("373"), issue!("875")],
        evidence: WORKSPACE,
        supporting_evidence: &[PRODUCTION_HOST, STAGE2_JOURNEY],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-REQ-002",
        owners: &["OWN-PLAIN", "OWN-MODEL"],
        implementation_issues: &[issue!("376"), issue!("377"), issue!("879")],
        evidence: FAKE_DECISION,
        supporting_evidence: &[OPEN_BLOCK, PRODUCTION_HOST],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-REQ-003",
        owners: &[
            "OWN-CTX",
            "OWN-AGENT",
            "OWN-MODEL",
            "OWN-PROTO",
            "OWN-PG",
            "OWN-TRUST",
        ],
        implementation_issues: &[
            issue!("374"),
            issue!("689"),
            issue!("690"),
            issue!("375"),
            issue!("851"),
            issue!("876"),
            issue!("877"),
        ],
        evidence: CREATE_RUN,
        supporting_evidence: &[CONTINUE, ADMITTED_TARGET, CAPTURED_MEMORY, RUN_EVIDENCE],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-REQ-004",
        owners: &["OWN-CORE", "OWN-ADM", "OWN-WEB"],
        implementation_issues: &[
            issue!("377"),
            issue!("378"),
            issue!("379"),
            issue!("380"),
            issue!("382"),
            issue!("879"),
        ],
        evidence: PRODUCTION_HOST,
        supporting_evidence: &[
            ACCEPT,
            REJECT,
            OPEN_BLOCK,
            CANDIDATE_EDIT,
            INLINE_PRODUCTION,
            MULTI,
        ],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-REQ-005",
        owners: &["OWN-CORE", "OWN-WEB", "OWN-AGENT"],
        implementation_issues: &[issue!("383"), issue!("376")],
        evidence: STREAM,
        supporting_evidence: &[PRODUCTION_HOST],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-REQ-006",
        owners: &["OWN-MODEL", "OWN-CTX", "OWN-DVG", "OWN-RET"],
        implementation_issues: &[
            issue!("690"),
            issue!("691"),
            issue!("692"),
            issue!("693"),
            issue!("694"),
            issue!("390"),
            issue!("376"),
            issue!("875"),
            issue!("877"),
        ],
        evidence: CONTINUE,
        supporting_evidence: &[
            COMPACT,
            EXPIRY,
            LOOKUP,
            SUCCESSOR,
            CANCEL,
            PRODUCTION_HOST,
            RUN_EVIDENCE,
        ],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-REQ-007",
        owners: &["OWN-REL", "OWN-WEB", "OWN-CORE", "OWN-PG"],
        implementation_issues: &[issue!("280")],
        evidence: STAGE2_JOURNEY,
        supporting_evidence: &[PHYSICAL_SCRIPT, PHYSICAL_DRILL],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-REQ-008",
        owners: &["OWN-CORE", "OWN-WEB", "OWN-ADM", "OWN-AGENT"],
        implementation_issues: &[
            issue!("381"),
            issue!("382"),
            issue!("383"),
            issue!("384"),
            issue!("387"),
            issue!("388"),
            issue!("389"),
            issue!("378"),
            issue!("879"),
        ],
        evidence: MULTI,
        supporting_evidence: &[
            STREAM,
            PARTIAL,
            CONTINUE_GENERATION,
            INLINE,
            UNDO,
            COMPARISON,
            PRODUCTION_HOST,
            CANDIDATE_EDIT,
            INLINE_PRODUCTION,
        ],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-EVD-001",
        owners: &["OWN-AGENT", "OWN-PLAIN", "OWN-REL"],
        implementation_issues: &[issue!("376"), issue!("374"), issue!("373"), issue!("875")],
        evidence: FAKE_DECISION,
        supporting_evidence: &[WORKSPACE, PRODUCTION_HOST],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-EVD-002",
        owners: &[
            "OWN-CTX",
            "OWN-AGENT",
            "OWN-MODEL",
            "OWN-TRUST",
            "OWN-PROTO",
            "OWN-PG",
        ],
        implementation_issues: &[
            issue!("689"),
            issue!("374"),
            issue!("690"),
            issue!("375"),
            issue!("851"),
            issue!("876"),
            issue!("877"),
        ],
        evidence: CREATE_RUN,
        supporting_evidence: &[CONTINUE, ADMITTED_TARGET, CAPTURED_MEMORY, RUN_EVIDENCE],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-EVD-003",
        owners: &["OWN-CORE", "OWN-ADM", "OWN-WEB"],
        implementation_issues: &[
            issue!("377"),
            issue!("381"),
            issue!("385"),
            issue!("386"),
            issue!("824"),
            issue!("825"),
            issue!("826"),
            issue!("827"),
            issue!("831"),
            issue!("832"),
            issue!("840"),
            issue!("378"),
            issue!("382"),
            issue!("879"),
        ],
        evidence: INLINE,
        supporting_evidence: &[
            OPEN_BLOCK,
            WITHDRAW,
            PRODUCTION_HOST,
            "apps/web/test/browser-exact-dist/restored-discard.integration.test.ts",
            "apps/web/test/browser-source/refused-edit-discard.integration.test.ts",
            CANDIDATE_EDIT,
            INLINE_PRODUCTION,
            MULTI,
        ],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-EVD-004",
        owners: &["OWN-CORE", "OWN-ADM", "OWN-WEB"],
        implementation_issues: &[issue!("379"), issue!("380"), issue!("382"), issue!("879")],
        evidence: ACCEPT,
        supporting_evidence: &[REJECT, PRODUCTION_HOST, MULTI, INLINE_PRODUCTION],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-EVD-005",
        owners: &["OWN-CTX", "OWN-CORE", "OWN-PG", "OWN-RET"],
        implementation_issues: &[
            issue!("692"),
            issue!("693"),
            issue!("694"),
            issue!("390"),
            issue!("690"),
            issue!("875"),
            issue!("877"),
        ],
        evidence: SUCCESSOR,
        supporting_evidence: &[
            EXPIRY,
            LOOKUP,
            CANCEL,
            COMPACT,
            PRODUCTION_HOST,
            RUN_EVIDENCE,
        ],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-EVD-006",
        owners: &["OWN-MODEL", "OWN-REL", "OWN-DVG"],
        implementation_issues: &[
            issue!("376"),
            issue!("690"),
            issue!("691"),
            issue!("875"),
            issue!("877"),
        ],
        evidence: COMPACT,
        supporting_evidence: &[FAKE_DECISION, CONTINUE, PRODUCTION_HOST, RUN_EVIDENCE],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-EVD-007",
        owners: &["OWN-REL", "OWN-WEB", "OWN-CORE", "OWN-PG"],
        implementation_issues: &[issue!("280"), issue!("278")],
        evidence: STAGE2_JOURNEY,
        supporting_evidence: &[PHYSICAL_SCRIPT, PHYSICAL_DRILL],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-EVD-008",
        owners: &["OWN-CORE", "OWN-WEB", "OWN-DVG"],
        implementation_issues: &[
            issue!("382"),
            issue!("383"),
            issue!("384"),
            issue!("388"),
            issue!("389"),
            issue!("378"),
            issue!("879"),
        ],
        evidence: MULTI,
        supporting_evidence: &[
            COMPARISON,
            UNDO,
            STREAM,
            PARTIAL,
            CONTINUE_GENERATION,
            INLINE,
            PRODUCTION_HOST,
            OPEN_BLOCK,
            CANDIDATE_EDIT,
            INLINE_PRODUCTION,
        ],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-JRN-001",
        owners: &[
            "OWN-REL",
            "OWN-PLAIN",
            "OWN-CTX",
            "OWN-AGENT",
            "OWN-CORE",
            "OWN-WEB",
        ],
        implementation_issues: &[
            TICKET_ISSUE,
            issue!("384"),
            issue!("373"),
            issue!("375"),
            issue!("377"),
            issue!("378"),
            issue!("382"),
            issue!("690"),
            issue!("851"),
            issue!("875"),
            issue!("876"),
            issue!("877"),
            issue!("879"),
        ],
        evidence: PRODUCTION_HOST,
        supporting_evidence: &[
            STAGE2_JOURNEY,
            CREATE_RUN,
            CONTINUE,
            COMPACT,
            ACCEPT,
            REJECT,
            EXPIRY,
            LOOKUP,
            SUCCESSOR,
            CANCEL,
            UNDO,
            STREAM,
            PARTIAL,
            CONTINUE_GENERATION,
            MULTI,
            INLINE,
            OPEN_BLOCK,
            FAKE_DECISION,
            WORKSPACE,
            ADMITTED_TARGET,
            CANDIDATE_EDIT,
            INLINE_PRODUCTION,
            CAPTURED_MEMORY,
            RUN_EVIDENCE,
        ],
        evidence_class: EvidenceClass::Stage,
    },
    Binding {
        id: "S3-JRN-001/1",
        owners: &["OWN-REL", "OWN-WEB", "OWN-PG"],
        implementation_issues: &[issue!("280"), issue!("373")],
        evidence: STAGE2_JOURNEY,
        supporting_evidence: &[WORKSPACE, PRODUCTION_HOST],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-JRN-001/2",
        owners: &["OWN-WEB", "OWN-AGENT", "OWN-CTX"],
        implementation_issues: &[
            issue!("374"),
            issue!("373"),
            issue!("377"),
            issue!("382"),
            issue!("875"),
            issue!("879"),
        ],
        evidence: PRODUCTION_HOST,
        supporting_evidence: &[CREATE_RUN, ADMITTED_TARGET, OPEN_BLOCK],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-JRN-001/3",
        owners: &["OWN-CTX", "OWN-AGENT", "OWN-MODEL", "OWN-PG"],
        implementation_issues: &[
            issue!("689"),
            issue!("690"),
            issue!("376"),
            issue!("375"),
            issue!("851"),
            issue!("876"),
            issue!("877"),
        ],
        evidence: CREATE_RUN,
        supporting_evidence: &[
            CONTINUE,
            FAKE_DECISION,
            ADMITTED_TARGET,
            CAPTURED_MEMORY,
            RUN_EVIDENCE,
        ],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-JRN-001/4",
        owners: &["OWN-CORE", "OWN-ADM", "OWN-WEB"],
        implementation_issues: &[
            issue!("378"),
            issue!("379"),
            issue!("380"),
            issue!("382"),
            issue!("879"),
        ],
        evidence: PRODUCTION_HOST,
        supporting_evidence: &[ACCEPT, REJECT, CANDIDATE_EDIT, INLINE_PRODUCTION, MULTI],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-JRN-001/5",
        owners: &["OWN-CTX", "OWN-CORE", "OWN-PG", "OWN-RET"],
        implementation_issues: &[
            issue!("386"),
            issue!("390"),
            issue!("692"),
            issue!("693"),
            issue!("694"),
            issue!("840"),
            issue!("690"),
            issue!("875"),
            issue!("877"),
        ],
        evidence: PRODUCTION_HOST,
        supporting_evidence: &[
            EXPIRY,
            LOOKUP,
            SUCCESSOR,
            CANCEL,
            CONTINUE,
            COMPACT,
            RUN_EVIDENCE,
        ],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-JRN-001/6",
        owners: &["OWN-CORE", "OWN-WEB", "OWN-ADM"],
        implementation_issues: &[
            issue!("381"),
            issue!("382"),
            issue!("383"),
            issue!("384"),
            issue!("388"),
            issue!("389"),
            issue!("378"),
            issue!("879"),
        ],
        evidence: UNDO,
        supporting_evidence: &[
            STREAM,
            PARTIAL,
            CONTINUE_GENERATION,
            MULTI,
            INLINE,
            COMPARISON,
            OPEN_BLOCK,
            CANDIDATE_EDIT,
            INLINE_PRODUCTION,
            PRODUCTION_HOST,
        ],
        evidence_class: EvidenceClass::Integration,
    },
    Binding {
        id: "S3-JRN-001/7",
        owners: &["OWN-REL", "OWN-WEB", "OWN-CORE", "OWN-PG"],
        implementation_issues: &[issue!("280")],
        evidence: STAGE2_JOURNEY,
        supporting_evidence: &[PHYSICAL_SCRIPT],
        evidence_class: EvidenceClass::Integration,
    },
];
